### ISSUE TITLE
Support key rotation

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/go-wallet#243]
In order for the validators to change their vega public key, we need the vega network to be able to rotate key from a validator.
We need for the wallet to be able to:
- expose an ID (public master key)
- extract / isolate a key pair from a wallet (so the master key is kept safe somewhere)

### Tasks
- [ ] Create / expose the wallet ID
- [ ] Create a new wallet type to extract a keypair
- [ ] Make sure a node or user can sign transaction with such wallet
